version: '3'
services:
  notebox:
    build: ./
    command: sleep infinity
    restart: unless-stopped
    volumes:
      - ..:/usr/src/notebox:cached
      - ~/.ssh:/home/node/.ssh

volumes:
  db_data:
